apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout-service-monitor
  namespace: tenant-checkout
  labels:
    app: checkout-service
    service: checkout
    tenant: tenant-checkout
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: checkout-service
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
          action: replace
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: tenant
          action: replace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: job
          action: replace
        - targetLabel: service
          replacement: checkout
          action: replace
